project:
  type: book

book:
  title: "EUPM Practitioners Guide"
  # author: "TODO"
  date: "2/12/2025"
  chapters:
    - index.qmd
    - price-adj.qmd
    #- intro.qmd
    #- data.qmd
    # - fh.qmd
    #- ul.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: false
    code-tools: true
    code-overflow: wrap
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    highlight-style: github
    
  pdf:
    documentclass: scrreprt

editor: visual

