project:
  type: book

book:
  title: "EUPM Practitioners Guide"
  # author: "TODO"
  date: "2/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - data.qmd
    - fh.qmd
    - ul.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

